default_options: #--prune-name .git,.idea
languages:
  shell:
    extensions:
      - sh
    shebangs:
      - sh
      - bash
  go:
    extensions:
      - go
  java:
    extensions: 
      - java
  perl:
    extensions: 
      - pl
      - PL
    shebangs: 
      - perl
  maven: 
    names:
      - pom.xml
grep:
  options: --color=auto
